/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.proyectozoo_gui;


import Dominio.Clima;
import Dominio.Continente;
import Dominio.Habitat;
import Dominio.Vegetacion;
import com.mycompany.proyectozoo_logica.FabricaLogica;
import com.mycompany.proyectozoo_logica.ILogica;
import java.util.ArrayList;
import java.util.List;
import java.util.Set;

import javax.swing.DefaultListModel;
import javax.swing.JList;
import javax.swing.JOptionPane;

/**
 *
 * @author diego
 */
public class frmRegistrarHabitat extends javax.swing.JFrame {
        DefaultListModel<Continente> modeloListaContinentesDisponibles = new DefaultListModel<>();
        DefaultListModel<Continente> modeloListaContinentesSeleccionados = new DefaultListModel<>();
        ILogica logica;
    /**
     * Creates new form RegistrarHabitat
     */
    public frmRegistrarHabitat() {
        
        logica =FabricaLogica.crearInstancia();
        initComponents();
        listaContinentesDisponibles.setModel(modeloListaContinentesDisponibles);
        listaContinentesSeleccionados.setModel(modeloListaContinentesSeleccionados);
       
    }
    
    public frmRegistrarHabitat(List<Continente> lcl,List<Clima> lc,List<Vegetacion> lv) {
        logica =FabricaLogica.crearInstancia();
        initComponents();
        listaContinentesDisponibles.setModel(modeloListaContinentesDisponibles);
        listaContinentesSeleccionados.setModel(modeloListaContinentesSeleccionados);
        this.llenarDatos(lcl, lc, lv);
    }
    
    public void llenarDatos(List<Continente> lcl,List<Clima> lc,List<Vegetacion> lv){
        modeloListaContinentesSeleccionados.removeAllElements();
        for (Continente con:lcl) {
            modeloListaContinentesDisponibles.addElement(con);
        }
        for (Clima cli:lc) {
            cmbClimas.addItem(cli);
        }
        for (Vegetacion vege:lv) {
            cmbVegetacion.addItem(vege);
        }
    }
    public void activarCampos(){
        btnVerificar.setEnabled(false);
        btnRegistrar.setEnabled(true);
        cmbVegetacion.setEnabled(true);
        cmbClimas.setEnabled(true);
        listaContinentesSeleccionados.setEnabled(true);
        listaContinentesDisponibles.setEnabled(true);
        
    }
    public void desactivarCampos(){
        btnVerificar.setEnabled(true);
        btnRegistrar.setEnabled(false);
        cmbVegetacion.setEnabled(false);
        cmbClimas.setEnabled(false);
        listaContinentesSeleccionados.setEnabled(false);
        listaContinentesDisponibles.setEnabled(false);
        for (int i = 0; i < modeloListaContinentesSeleccionados.size(); i++) {
            
        }
        
    }
    public void mostrarHabitat(Habitat habitat){
        JOptionPane.showMessageDialog(this, "Nombre de Habitat , No disponible");
         for (Continente c :habitat.getContinentes()) {
             for (int i = 0; i < modeloListaContinentesDisponibles.size(); i++) {
                 if (modeloListaContinentesDisponibles.get(i).equals(c)) {
                     modeloListaContinentesSeleccionados.addElement(c);
                     modeloListaContinentesDisponibles.remove(i);
                 }
             }
 
         }
            
        
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        cmbClimas = new javax.swing.JComboBox<>();
        cmbVegetacion = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtNombreHabitat = new javax.swing.JTextField();
        btnVerificar = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jScrollPane1 = new javax.swing.JScrollPane();
        listaContinentesDisponibles = new javax.swing.JList<>();
        jScrollPane2 = new javax.swing.JScrollPane();
        listaContinentesSeleccionados = new javax.swing.JList<>();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        btnRegistrar = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Registrar Habitat");

        cmbClimas.setEnabled(false);
        cmbClimas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbClimasActionPerformed(evt);
            }
        });

        cmbVegetacion.setEnabled(false);

        jLabel2.setText("Climas");

        jLabel3.setText("Vegetacion");

        txtNombreHabitat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNombreHabitatActionPerformed(evt);
            }
        });

        btnVerificar.setText("Verificar");
        btnVerificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVerificarActionPerformed(evt);
            }
        });

        jLabel4.setText("Ingrese Nombre Habitats");

        listaContinentesDisponibles.setEnabled(false);
        listaContinentesDisponibles.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                listaContinentesDisponiblesMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(listaContinentesDisponibles);

        listaContinentesSeleccionados.setEnabled(false);
        listaContinentesSeleccionados.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                listaContinentesSeleccionadosMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(listaContinentesSeleccionados);

        jLabel5.setText("Continentes");

        jLabel6.setText("Continentes");

        jLabel7.setText("Disponibles");

        jLabel8.setText("Seleccionados");

        btnRegistrar.setText("Registrar Habitat");
        btnRegistrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarActionPerformed(evt);
            }
        });

        jButton1.setText("Cancelar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setBackground(new java.awt.Color(153, 0, 51));
        jButton2.setText("X");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(50, 50, 50)
                                        .addComponent(jLabel3))
                                    .addComponent(cmbVegetacion, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 163, Short.MAX_VALUE)
                                .addComponent(btnRegistrar))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(22, 22, 22)
                                .addComponent(jButton1)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel1))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(50, 50, 50)
                                .addComponent(jLabel4))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(50, 50, 50)
                                .addComponent(txtNombreHabitat, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(7, 7, 7)
                                .addComponent(btnVerificar)
                                .addGap(18, 18, 18)
                                .addComponent(jButton2))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(50, 50, 50)
                                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 251, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(50, 50, 50)
                                .addComponent(jLabel2))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(50, 50, 50)
                                .addComponent(cmbClimas, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(50, 50, 50)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel7)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel8)
                                            .addComponent(jLabel6))))))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGap(74, 74, 74))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(9, 9, 9)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jButton1))
                .addGap(13, 13, 13)
                .addComponent(jLabel4)
                .addGap(7, 7, 7)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(txtNombreHabitat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnVerificar)
                        .addComponent(jButton2)))
                .addGap(7, 7, 7)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(7, 7, 7)
                .addComponent(jLabel2)
                .addGap(7, 7, 7)
                .addComponent(cmbClimas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(7, 7, 7)
                        .addComponent(jLabel3)
                        .addGap(9, 9, 9)
                        .addComponent(cmbVegetacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(btnRegistrar)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jLabel8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnVerificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVerificarActionPerformed
        if (!txtNombreHabitat.getText().isEmpty()) {
            Habitat habitat=logica.verificaNombreHabitat(txtNombreHabitat.getText());
            reiniciarContinentes();
            if(habitat!=null){
                mostrarHabitat(habitat);
            }else{
              activarCampos();
            }
        }

    }//GEN-LAST:event_btnVerificarActionPerformed

    private void listaContinentesDisponiblesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_listaContinentesDisponiblesMouseClicked
                if (evt.getClickCount() == 2) {
                    Continente selectedValue = listaContinentesDisponibles.getSelectedValue();
                    if (selectedValue != null) {
                        modeloListaContinentesSeleccionados.addElement(selectedValue);
                        modeloListaContinentesDisponibles.removeElement(selectedValue);
                    }
                }
    }//GEN-LAST:event_listaContinentesDisponiblesMouseClicked

    private void listaContinentesSeleccionadosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_listaContinentesSeleccionadosMouseClicked
       if (evt.getClickCount() == 2) {
                    Continente selectedValue = listaContinentesSeleccionados.getSelectedValue();
                    if (selectedValue != null) {
                        modeloListaContinentesDisponibles.addElement(selectedValue);
                        modeloListaContinentesSeleccionados.removeElement(selectedValue);
                    }
                }
    }//GEN-LAST:event_listaContinentesSeleccionadosMouseClicked

    private void txtNombreHabitatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNombreHabitatActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombreHabitatActionPerformed

    private void btnRegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarActionPerformed
        if (validadCampos()) {
            registrarHabitat();
        }
    }//GEN-LAST:event_btnRegistrarActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
          this.dispose();
        logica.abrirMenu();
    
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
    txtNombreHabitat.setText("");
    desactivarCampos();
    reiniciarContinentes();
        
    }//GEN-LAST:event_jButton2ActionPerformed

    private void cmbClimasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbClimasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbClimasActionPerformed
    public void registrarHabitat(){
        Habitat h = new Habitat();
        h.setNombre(txtNombreHabitat.getText());
        List<Continente> seleccionados = new ArrayList<>();
        for (int i = 0; i < modeloListaContinentesSeleccionados.size(); i++) {
            seleccionados.add(modeloListaContinentesSeleccionados.get(i));
        }
        h.setContinentes(seleccionados);
        h.setClima((Clima) cmbClimas.getSelectedItem());
        h.setVegetacion((Vegetacion) cmbVegetacion.getSelectedItem());
        
        if (logica.guardarHabitat(h)) {
            JOptionPane.showMessageDialog(this, "Registro Exitoso");
            this.dispose();
            logica.abrirMenu();
        }else{
            JOptionPane.showMessageDialog(this, "Error al Registrar");
        }
        
    }
    public void reiniciarContinentes(){
        while(!modeloListaContinentesSeleccionados.isEmpty()){
            modeloListaContinentesDisponibles.addElement(modeloListaContinentesSeleccionados.get(0));
            modeloListaContinentesSeleccionados.remove(0);
        }
        
    }
   
    public boolean validadCampos(){
        if (txtNombreHabitat.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Indique un Nombre de Habitat,Porfavor");
            return false;
        }
        if (modeloListaContinentesSeleccionados.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Selecione minimo 1 Continente");
            return false; 
        }   
        return true;
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmRegistrarHabitat.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmRegistrarHabitat.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmRegistrarHabitat.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmRegistrarHabitat.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmRegistrarHabitat().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnRegistrar;
    private javax.swing.JButton btnVerificar;
    private javax.swing.JComboBox<Clima> cmbClimas;
    private javax.swing.JComboBox<Vegetacion> cmbVegetacion;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JList<Continente> listaContinentesDisponibles;
    private javax.swing.JList<Continente> listaContinentesSeleccionados;
    private javax.swing.JTextField txtNombreHabitat;
    // End of variables declaration//GEN-END:variables
}
